common: &common
  adapter: postgresql
  host: localhost
  port: 5432

development:
  <<: *common
  database: rails_development

test:
  <<: *common
  database: rails_test

production:
  <<: *common
  database: rails_production
