common: &common
  adapter: postgresql
  username: rails
  password: password

development:
  <<: *common
  database: rails_development

test:
  <<: *common
  database: rails_test

production:
  <<: *common
  database: rails_production
